### PR TITLE
preparing for Xcode 9

### PR DESCRIPTION
**Pull request by Maryom**

### CODE REVIEW

**Comment by Mazyod** [comment]
Can please also add Xcode 9 testing to .travis.yml

**Comment by Maryom** [comment]
In readme I just changed Mazyod to Maz so that I can push it again, I don't know why it appears that I changed a lot of things in readme.

**Comment by Mazyod** [comment]
it's fine, you just also need to change the SDKs in .travis.yml to Xcode 9 SDKs

**Comment by Mazyod** [comment]
I committed directly, let's see what happens

**Comment by Maryom** [comment]
Do we need to add Xcode 9 testing to .travis.yml to all Kitz repo.s ?

**Comment by Mazyod** [comment]
Yes please 😊  But first, let's make sure we get it right here

**Comment by Maryom** [comment]
Ok, I will do it tomorrow إن شاء الله

**Comment by Maryom** [comment]
Do you want to change your name to Maz in all Kitz repo.s ?

**Comment by Mazyod** [comment]
I don't think it matters

**Comment by Mazyod** [comment]
But we should change the shield in the Readme to `Swift 4`

**Comment by Maryom** [comment]
In master branch ? or `Swift 4` should be in Swift 4 branch ?

I think it's better to change your name to Maz so that all repo.s have same info. (consistency). Shall I change it ?

**Comment by Mazyod** [comment]
Master branch is fine, people should be using versioning anyway.
I still think whether my name is changed or not doesn't matter.

**Pull request merged**
